namespace BibleJson.Services
{
    public class BibleTranslate
    {
        public static string TranslateToEnglish(string title)
        {
            return title switch
            {
                "Gênesis" => "Genesis",
                "Êxodo" => "Exodus",
                "Levítico" => "Leviticus",
                "Números" => "Numbers",
                "Deuteronômio" => "Deuteronomy",
                "Josué" => "Joshua",
                "Juízes" => "Judges",
                "Rute" => "Ruth",
                "1 Samuel" => "1 Samuel",
                "2 Samuel" => "2 Samuel",
                "1 Reis" => "1 Kings",
                "2 Reis" => "2 Kings",
                "1 Crônicas" => "1 Chronicles",
                "2 Crônicas" => "2 Chronicles",
                "Esdras" => "Ezra",
                "Neemias" => "Nehemiah",
                "Ester" => "Esther",
                "Jó" => "Job",
                "Salmos" => "Psalms",
                "Provérbios" => "Proverbs",
                "Eclesiastes" => "Ecclesiastes",
                "Cânticos" => "Song of Solomon",
                "Isaías" => "Isaiah",
                "Jeremias" => "Jeremiah",
                "Lamentações" => "Lamentations",
                "Ezequiel" => "Ezekiel",
                "Daniel" => "Daniel",
                "Oséias" => "Hosea",
                "Joel" => "Joel",
                "Amós" => "Amos",
                "Obadias" => "Obadiah",
                "Jonas" => "Jonah",
                "Miquéias" => "Micah",
                "Naum" => "Nahum",
                "Habacuque" => "Habakkuk",
                "Sofonias" => "Zephaniah",
                "Ageu" => "Haggai",
                "Zacarias" => "Zechariah",
                "Malaquias" => "Malachi",
                "Mateus" => "Matthew",
                "Marcos" => "Mark",
                "Lucas" => "Luke",
                "João" => "John",
                "Atos" => "Acts",
                "Romanos" => "Romans",
                "1 Coríntios" => "1 Corinthians",
                "2 Coríntios" => "2 Corinthians",
                "Gálatas" => "Galatians",
                "Efésios" => "Ephesians",
                "Filipenses" => "Philippians",
                "Colossenses" => "Colossians",
                "1 Tessalonicenses" => "1 Thessalonians",
                "2 Tessalonicenses" => "2 Thessalonians",
                "1 Timóteo" => "1 Timothy",
                "2 Timóteo" => "2 Timothy",
                "Tito" => "Titus",
                "Filemom" => "Philemon",
                "Hebreus" => "Hebrews",
                "Tiago" => "James",
                "1 Pedro" => "1 Peter",
                "2 Pedro" => "2 Peter",
                "1 João" => "1 John",
                "2 João" => "2 John",
                "3 João" => "3 John",
                "Judas" => "Jude",
                "Apocalipse" => "Revelation",
                _ => title
            };
        }

        public static string TranslateToFrench(string title)
        {
            return title switch
            {
                "Gênesis" => "Genèse",
                "Êxodo" => "Exode",
                "Levítico" => "Lévitique",
                "Números" => "Nombres",
                "Deuteronômio" => "Deutéronome",
                "Josué" => "Josué",
                "Juízes" => "Juges",
                "Rute" => "Ruth",
                "1 Samuel" => "1 Samuel",
                "2 Samuel" => "2 Samuel",
                "1 Reis" => "1 Rois",
                "2 Reis" => "2 Rois",
                "1 Crônicas" => "1 Chroniques",
                "2 Crônicas" => "2 Chroniques",
                "Esdras" => "Esdras",
                "Neemias" => "Néhémie",
                "Ester" => "Esther",
                "Jó" => "Job",
                "Salmos" => "Psaumes",
                "Provérbios" => "Proverbes",
                "Eclesiastes" => "Ecclésiaste",
                "Cânticos" => "Cantique des Cantiques",
                "Isaías" => "Ésaïe",
                "Jeremias" => "Jérémie",
                "Lamentações" => "Lamentations",
                "Ezequiel" => "Ézéchiel",
                "Daniel" => "Daniel",
                "Oséias" => "Osée",
                "Joel" => "Joël",
                "Amós" => "Amos",
                "Obadias" => "Abdias",
                "Jonas" => "Jonas",
                "Miquéias" => "Michée",
                "Naum" => "Nahum",
                "Habacuque" => "Habacuc",
                "Sofonias" => "Sophonie",
                "Ageu" => "Aggée",
                "Zacarias" => "Zacharie",
                "Malaquias" => "Malachie",
                "Mateus" => "Matthieu",
                "Marcos" => "Marc",
                "Lucas" => "Luc",
                "João" => "Jean",
                "Atos" => "Actes",
                "Romanos" => "Romains",
                "1 Coríntios" => "1 Corinthiens",
                "2 Coríntios" => "2 Corinthiens",
                "Gálatas" => "Galates",
                "Efésios" => "Éphésiens",
                "Filipenses" => "Philippiens",
                "Colossenses" => "Colossiens",
                "1 Tessalonicenses" => "1 Thessaloniciens",
                "2 Tessalonicenses" => "2 Thessaloniciens",
                "1 Timóteo" => "1 Timothée",
                "2 Timóteo" => "2 Timothée",
                "Tito" => "Tite",
                "Filemom" => "Philémon",
                "Hebreus" => "Hébreux",
                "Tiago" => "Jacques",
                "1 Pedro" => "1 Pierre",
                "2 Pedro" => "2 Pierre",
                "1 João" => "1 Jean",
                "2 João" => "2 Jean",
                "3 João" => "3 Jean",
                "Judas" => "Jude",
                "Apocalipse" => "Apocalypse",
                _ => title
            };
        }

        public static string TranslateToSpanish(string title)
        {
            return title switch
            {
                "Gênesis" => "Génesis",
                "Êxodo" => "Éxodo",
                "Levítico" => "Levítico",
                "Números" => "Números",
                "Deuteronômio" => "Deuteronomio",
                "Josué" => "Josué",
                "Juízes" => "Jueces",
                "Rute" => "Rut",
                "1 Samuel" => "1 Samuel",
                "2 Samuel" => "2 Samuel",
                "1 Reis" => "1 Reyes",
                "2 Reis" => "2 Reyes",
                "1 Crônicas" => "1 Crónicas",
                "2 Crônicas" => "2 Crónicas",
                "Esdras" => "Esdras",
                "Neemias" => "Nehemías",
                "Ester" => "Ester",
                "Jó" => "Job",
                "Salmos" => "Salmos",
                "Provérbios" => "Proverbios",
                "Eclesiastes" => "Eclesiastés",
                "Cânticos" => "Cantares",
                "Isaías" => "Isaías",
                "Jeremias" => "Jeremías",
                "Lamentações" => "Lamentaciones",
                "Ezequiel" => "Ezequiel",
                "Daniel" => "Daniel",
                "Oséias" => "Oseas",
                "Joel" => "Joel",
                "Amós" => "Amós",
                "Obadias" => "Abdías",
                "Jonas" => "Jonás",
                "Miquéias" => "Miqueas",
                "Naum" => "Nahúm",
                "Habacuque" => "Habacuc",
                "Sofonias" => "Sofonías",
                "Ageu" => "Hageo",
                "Zacarias" => "Zacarías",
                "Malaquias" => "Malaquías",
                "Mateus" => "Mateo",
                "Marcos" => "Marcos",
                "Lucas" => "Lucas",
                "João" => "Juan",
                "Atos" => "Hechos",
                "Romanos" => "Romanos",
                "1 Coríntios" => "1 Corintios",
                "2 Coríntios" => "2 Corintios",
                "Gálatas" => "Gálatas",
                "Efésios" => "Efesios",
                "Filipenses" => "Filipenses",
                "Colossenses" => "Colosenses",
                "1 Tessalonicenses" => "1 Tesalonicenses",
                "2 Tessalonicenses" => "2 Tesalonicenses",
                "1 Timóteo" => "1 Timoteo",
                "2 Timóteo" => "2 Timoteo",
                "Tito" => "Tito",
                "Filemom" => "Filemón",
                "Hebreus" => "Hebreos",
                "Tiago" => "Santiago",
                "1 Pedro" => "1 Pedro",
                "2 Pedro" => "2 Pedro",
                "1 João" => "1 Juan",
                "2 João" => "2 Juan",
                "3 João" => "3 Juan",
                "Judas" => "Judas",
                "Apocalipse" => "Apocalipsis",
                _ => title
            };
        }

        public static string TranslateToItalian(string title)
        {
            return title switch
            {
                "Gênesis" => "Genesi",
                "Êxodo" => "Esodo",
                "Levítico" => "Levitico",
                "Números" => "Numeri",
                "Deuteronômio" => "Deuteronomio",
                "Josué" => "Giosuè",
                "Juízes" => "Giudici",
                "Rute" => "Rut",
                "1 Samuel" => "1 Samuele",
                "2 Samuel" => "2 Samuele",
                "1 Reis" => "1 Re",
                "2 Reis" => "2 Re",
                "1 Crônicas" => "1 Cronache",
                "2 Crônicas" => "2 Cronache",
                "Esdras" => "Esdra",
                "Neemias" => "Neemia",
                "Ester" => "Ester",
                "Jó" => "Giobbe",
                "Salmos" => "Salmi",
                "Provérbios" => "Proverbi",
                "Eclesiastes" => "Ecclesiaste",
                "Cânticos" => "Cantico",
                "Isaías" => "Isaia",
                "Jeremias" => "Geremia",
                "Lamentações" => "Lamentazioni",
                "Ezequiel" => "Ezechiele",
                "Daniel" => "Daniele",
                "Oséias" => "Osea",
                "Joel" => "Gioele",
                "Amós" => "Amos",
                "Obadias" => "Abdia",
                "Jonas" => "Giona",
                "Miquéias" => "Michea",
                "Naum" => "Naum",
                "Habacuque" => "Abacuc",
                "Sofonias" => "Sofonia",
                "Ageu" => "Aggeo",
                "Zacarias" => "Zaccaria",
                "Malaquias" => "Malachia",
                "Mateus" => "Matteo",
                "Marcos" => "Marco",
                "Lucas" => "Luca",
                "João" => "Giovanni",
                "Atos" => "Atti",
                "Romanos" => "Romani",
                "1 Coríntios" => "1 Corinzi",
                "2 Coríntios" => "2 Corinzi",
                "Gálatas" => "Galati",
                "Efésios" => "Efesini",
                "Filipenses" => "Filippesi",
                "Colossenses" => "Colossesi",
                "1 Tessalonicenses" => "1 Tessalonicesi",
                "2 Tessalonicenses" => "2 Tessalonicesi",
                "1 Timóteo" => "1 Timoteo",
                "2 Timóteo" => "2 Timoteo",
                "Tito" => "Tito",
                "Filemom" => "Filemone",
                "Hebreus" => "Ebrei",
                "Tiago" => "Giacomo",
                "1 Pedro" => "1 Pietro",
                "2 Pedro" => "2 Pietro",
                "1 João" => "1 Giovanni",
                "2 João" => "2 Giovanni",
                "3 João" => "3 Giovanni",
                "Judas" => "Giuda",
                "Apocalipse" => "Apocalisse",
                _ => title
            };
        }
    }
}